spring.application.name=JwtDemo

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/jwt_db
spring.datasource.username=root
spring.datasource.password=Sumit@2004

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=BA6fZyWs744aR7JYW5XLgZ4sTsVkZ1f4cMzN2D6c6rA
app.jwt.expiration-ms=3600000